import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000';
const emptyPlan = {project_title:'',summary:'',goals:[],tasks:[],risks:[],recommended_order:[]};

async function api(path, options={}, token){
  const headers={'Content-Type':'application/json', ...(options.headers||{})};
  if(token) headers.Authorization=`Bearer ${token}`;
  const res=await fetch(`${API}${path}`, {...options, headers});
  const data=await res.json().catch(()=>({}));
  if(!res.ok) throw new Error(data.detail || `Request failed (${res.status})`);
  return data;
}

function App(){
  const [token,setToken]=useState(()=>localStorage.getItem('devflow_token')||'');
  const [user,setUser]=useState(null);
  const [authMode,setAuthMode]=useState('login');
  const [authForm,setAuthForm]=useState({username:'',email:'',password:''});
  const [projects,setProjects]=useState([]);
  const [selected,setSelected]=useState(null);
  const [tasks,setTasks]=useState([]);
  const [tab,setTab]=useState('overview');
  const [loading,setLoading]=useState(false);
  const [notice,setNotice]=useState('');
  const [error,setError]=useState('');
  const [projectForm,setProjectForm]=useState({name:'',description:''});
  const [taskForm,setTaskForm]=useState({title:'',description:'',priority:'Medium',status:'Todo'});
  const [idea,setIdea]=useState('');
  const [plan,setPlan]=useState(emptyPlan);
  const [copilotQuestion,setCopilotQuestion]=useState('What should I work on next?');
  const [copilot,setCopilot]=useState(null);

  const stats=useMemo(()=>({total:tasks.length,done:tasks.filter(t=>t.status==='Completed').length,active:tasks.filter(t=>t.status==='In Progress').length,critical:tasks.filter(t=>t.priority==='Critical').length}),[tasks]);
  const progress=stats.total?Math.round(stats.done/stats.total*100):0;

  useEffect(()=>{if(token) loadUser();},[token]);
  async function loadUser(){try{const me=await api('/auth/me',{},token);setUser(me);loadProjects();}catch{logout();}}
  async function loadProjects(){try{setProjects(await api('/projects',{},token));}catch(e){setError(e.message);}}
  async function selectProject(p){setSelected(p);setTab('overview');setPlan(emptyPlan);setCopilot(null);try{const d=await api(`/projects/${p.id}/tasks`,{},token);setTasks(d.tasks||[]);}catch(e){setError(e.message);}}
  function flash(message){setNotice(message);setError('');setTimeout(()=>setNotice(''),3500);}
  async function submitAuth(e){e.preventDefault();setLoading(true);setError('');try{if(authMode==='register'){await api('/auth/register',{method:'POST',body:JSON.stringify(authForm)});flash('Account created. You can now sign in.');setAuthMode('login');}else{const d=await api('/auth/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({username:authForm.username,password:authForm.password})},'');localStorage.setItem('devflow_token',d.access_token);setToken(d.access_token);}}catch(e){setError(e.message);}finally{setLoading(false);}}
  function logout(){localStorage.removeItem('devflow_token');setToken('');setUser(null);setProjects([]);setSelected(null);}
  async function createProject(e){e.preventDefault();if(!projectForm.name.trim())return;try{const d=await api('/projects',{method:'POST',body:JSON.stringify(projectForm)},token);setProjectForm({name:'',description:''});await loadProjects();flash('Project created');selectProject(d.project);}catch(e){setError(e.message);}}
  async function createTask(e){e.preventDefault();if(!selected||!taskForm.title.trim())return;try{await api('/tasks',{method:'POST',body:JSON.stringify({...taskForm,project_id:selected.id})},token);setTaskForm({title:'',description:'',priority:'Medium',status:'Todo'});await selectProject(selected);flash('Task added');}catch(e){setError(e.message);}}
  async function updateTask(id,patch){try{await api(`/tasks/${id}`,{method:'PUT',body:JSON.stringify(patch)},token);await selectProject(selected);}catch(e){setError(e.message);}}
  async function deleteTask(id){if(!confirm('Delete this task?'))return;try{await api(`/tasks/${id}`,{method:'DELETE'},token);await selectProject(selected);flash('Task deleted');}catch(e){setError(e.message);}}
  async function deleteProject(id){if(!confirm('Delete this project and its tasks?'))return;try{await api(`/projects/${id}`,{method:'DELETE'},token);setSelected(null);await loadProjects();flash('Project deleted');}catch(e){setError(e.message);}}
  async function generatePlan(e){e.preventDefault();if(!idea.trim())return;setLoading(true);try{setPlan(await api('/ai/generate-plan',{method:'POST',body:JSON.stringify({project_idea:idea})},token));flash('AI plan generated');}catch(e){setError(e.message);}finally{setLoading(false);}}
  async function applyPlan(){if(!selected)return;try{const d=await api('/ai/apply-plan',{method:'POST',body:JSON.stringify({project_id:selected.id,plan})},token);await selectProject(selected);flash(`${d.created_tasks?.length||0} AI tasks added`);setTab('tasks');}catch(e){setError(e.message);}}
  async function askCopilot(e){e.preventDefault();if(!selected)return;setLoading(true);try{setCopilot(await api('/ai/copilot',{method:'POST',body:JSON.stringify({project_id:selected.id,question:copilotQuestion})},token));}catch(e){setError(e.message);}finally{setLoading(false);}}

  if(!token||!user)return <Auth mode={authMode} setMode={setAuthMode} form={authForm} setForm={setAuthForm} submit={submitAuth} loading={loading} error={error} notice={notice}/>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><div><b>DevFlow</b><small>AI workspace</small></div></div><div className="side-label">WORKSPACE</div><button className={!selected?'nav active':'nav'} onClick={()=>{setSelected(null);setTab('overview')}}>⌂ Overview</button>{projects.map(p=><button key={p.id} className={selected?.id===p.id?'nav active':'nav'} onClick={()=>selectProject(p)}>▣ {p.name}</button>)}<div className="sidebar-bottom"><div className="user-mini"><span>{user.username?.[0]?.toUpperCase()}</span><div><b>{user.username}</b><small>{user.email}</small></div></div><button className="nav" onClick={logout}>↪ Sign out</button></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">PROJECT OPERATIONS</span><h1>{selected?selected.name:'Your command center'}</h1></div><div className="top-actions"><span className="status-dot">● API connected</span><button className="ghost" onClick={()=>{setSelected(null);loadProjects()}}>Refresh</button></div></header>{notice&&<div className="notice">✓ {notice}</div>}{error&&<div className="error">{error}</div>}{!selected?<Home projects={projects} setSelected={selectProject} form={projectForm} setForm={setProjectForm} create={createProject}/>:<ProjectView selected={selected} tab={tab} setTab={setTab} tasks={tasks} stats={stats} progress={progress} taskForm={taskForm} setTaskForm={setTaskForm} createTask={createTask} updateTask={updateTask} deleteTask={deleteTask} deleteProject={deleteProject} idea={idea} setIdea={setIdea} plan={plan} setPlan={setPlan} generatePlan={generatePlan} applyPlan={applyPlan} copilotQuestion={copilotQuestion} setCopilotQuestion={setCopilotQuestion} copilot={copilot} askCopilot={askCopilot} loading={loading}/>}</main></div>
}

function Auth({mode,setMode,form,setForm,submit,loading,error,notice}){return <div className="auth-page"><div className="auth-art"><div className="brand big"><span className="brand-mark">✦</span><div><b>DevFlow</b><small>AI workspace</small></div></div><div className="hero-copy"><span className="pill">AI-POWERED PRODUCTIVITY</span><h1>Ship better.<br/><em>Think smarter.</em></h1><p>Turn ideas into structured execution with an intelligent project workspace.</p></div><div className="floating-card"><b>✦ AI Project Planner</b><span>From idea → roadmap → tasks</span></div></div><div className="auth-panel"><div className="auth-box"><span className="eyebrow">WELCOME BACK</span><h2>{mode==='login'?'Sign in to DevFlow':'Create your workspace'}</h2><p className="muted">{mode==='login'?'Continue building something great.':'Start turning ambitious ideas into shipped work.'}</p>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}<form onSubmit={submit}>{<label>Username<input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label>}{mode==='register'&&<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>}<label>Password<input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="primary full" disabled={loading}>{loading?'Please wait…':mode==='login'?'Sign in →':'Create account →'}</button></form><p className="switch">{mode==='login'?'New to DevFlow?':'Already have an account?'} <button onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create account':'Sign in'}</button></p></div></div></div>}

function Home({projects,setSelected,form,setForm,create}){return <div className="content"><section className="hero-banner"><div><span className="pill">YOUR WORKSPACE</span><h2>Make progress<br/>visible.</h2><p>Organize projects, generate AI roadmaps, and keep momentum.</p></div><div className="orb">✦</div></section><div className="section-head"><div><span className="eyebrow">OVERVIEW</span><h2>Projects <span className="count">{projects.length}</span></h2></div></div><div className="grid projects-grid">{projects.map(p=><button className="project-card" key={p.id} onClick={()=>setSelected(p)}><div className="card-icon">✦</div><h3>{p.name}</h3><p>{p.description||'No description yet.'}</p><span className="card-link">Open project ↗</span></button>)}<form className="project-card create-card" onSubmit={create}><div className="card-icon">＋</div><h3>New project</h3><input placeholder="Project name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea placeholder="Short description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="primary">Create project →</button></form></div></div>}

function ProjectView(p){return <div className="content"><div className="project-heading"><div><span className="pill">PROJECT #{p.selected.id}</span><h2>{p.selected.name}</h2><p>{p.selected.description||'Build, track, and ship your next milestone.'}</p></div><button className="danger ghost" onClick={()=>p.deleteProject(p.selected.id)}>Delete project</button></div><div className="tabs"><button className={p.tab==='overview'?'active':''} onClick={()=>p.setTab('overview')}>Overview</button><button className={p.tab==='tasks'?'active':''} onClick={()=>p.setTab('tasks')}>Task board</button><button className={p.tab==='planner'?'active':''} onClick={()=>p.setTab('planner')}>✦ AI Planner</button><button className={p.tab==='copilot'?'active':''} onClick={()=>p.setTab('copilot')}>◉ Copilot</button></div>{p.tab==='overview'&&<Overview {...p}/>} {p.tab==='tasks'&&<Tasks {...p}/>} {p.tab==='planner'&&<Planner {...p}/>} {p.tab==='copilot'&&<Copilot {...p}/>}</div>}
function Overview({stats,progress,tasks,setTab}){return <><div className="stats grid"><Stat label="Total tasks" value={stats.total} icon="▦"/><Stat label="Completed" value={stats.done} icon="✓"/><Stat label="In progress" value={stats.active} icon="↗"/><Stat label="Critical" value={stats.critical} icon="!"/></div><div className="two-col"><section className="panel"><div className="panel-head"><h3>Delivery progress</h3><span>{progress}%</span></div><div className="progress"><span style={{width:`${progress}%`}}/></div><p className="muted">{stats.done} of {stats.total} tasks completed.</p><button className="secondary" onClick={()=>setTab('tasks')}>Open task board →</button></section><section className="panel"><div className="panel-head"><h3>Recent work</h3><button className="text-btn" onClick={()=>setTab('tasks')}>View all</button></div>{tasks.slice(0,4).map(t=><div className="mini-task" key={t.id}><span className={`priority ${t.priority.toLowerCase()}`}/><div><b>{t.title}</b><small>{t.status} · {t.priority}</small></div></div>)}{!tasks.length&&<p className="muted">No tasks yet. Use the AI Planner to generate a roadmap.</p>}</section></div></>}
function Stat({label,value,icon}){return <div className="stat panel"><span className="stat-icon">{icon}</span><small>{label}</small><strong>{value}</strong></div>}
function Tasks({tasks,taskForm,setTaskForm,createTask,updateTask,deleteTask}){const cols=['Todo','In Progress','Completed'];return <><form className="panel task-create" onSubmit={createTask}><div><h3>Add a task</h3><p className="muted">Keep the next action clear.</p></div><input required placeholder="Task title" value={taskForm.title} onChange={e=>setTaskForm({...taskForm,title:e.target.value})}/><select value={taskForm.priority} onChange={e=>setTaskForm({...taskForm,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select><button className="primary">Add task</button></form><div className="board">{cols.map(col=><section className="board-col" key={col}><div className="col-head"><h3>{col}</h3><span>{tasks.filter(t=>t.status===col).length}</span></div>{tasks.filter(t=>t.status===col).map(t=><article className="task-card" key={t.id}><div className="task-top"><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span><button className="icon-btn" onClick={()=>deleteTask(t.id)}>×</button></div><h4>{t.title}</h4><p>{t.description||'No description'}</p><select value={t.status} onChange={e=>updateTask(t.id,{status:e.target.value})}><option>Todo</option><option>In Progress</option><option>Completed</option></select></article>)}</section>)}</div></>}
function Planner({idea,setIdea,plan,setPlan,generatePlan,applyPlan,loading}){return <div className="ai-layout"><section className="panel ai-input"><span className="eyebrow">GENERATIVE WORKFLOW</span><h3>What are you building?</h3><p className="muted">Describe an idea and DevFlow will turn it into a practical execution plan.</p><form onSubmit={generatePlan}><textarea required minLength="10" value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Build an AI resume analyzer using FastAPI and React…"/><button className="primary full" disabled={loading}>{loading?'Generating…':'✦ Generate plan'}</button></form></section>{plan.project_title?<section className="panel plan"><div className="plan-head"><div><span className="pill">AI GENERATED</span><h3>{plan.project_title}</h3></div><button className="primary" onClick={applyPlan}>Approve & add tasks →</button></div><p>{plan.summary}</p><h4>Goals</h4><ul>{plan.goals.map((x,i)=><li key={i}>{x}</li>)}</ul><h4>Execution plan</h4>{plan.tasks.map((t,i)=><div className="plan-task" key={i}><span>{String(i+1).padStart(2,'0')}</span><div><b>{t.title}</b><p>{t.description}</p><small>{t.priority} · {t.estimated_hours}h</small></div></div>)}</section>:<section className="panel empty-ai"><div>✦</div><h3>Your roadmap will appear here</h3><p className="muted">Generate a plan, review the tasks, then approve it into your project.</p></section>}</div>}
function Copilot({copilotQuestion,setCopilotQuestion,copilot,askCopilot,loading}){return <div className="copilot panel"><div className="copilot-title"><span className="ai-avatar">✦</span><div><h3>DevFlow Copilot</h3><p className="muted">Your project-aware AI assistant</p></div></div><form onSubmit={askCopilot} className="copilot-form"><input value={copilotQuestion} onChange={e=>setCopilotQuestion(e.target.value)} placeholder="Ask about your project…"/><button className="primary" disabled={loading}>Ask ↗</button></form>{copilot?<div className="copilot-answer"><span className="pill">COPILOT RESPONSE</span><p>{copilot.copilot?.answer||'No answer returned.'}</p><h4>Recommended actions</h4><ul>{(copilot.copilot?.recommended_actions||[]).map((x,i)=><li key={i}>{x}</li>)}</ul></div>:<div className="empty-ai"><div>◉</div><h3>Ask what to do next</h3><p className="muted">Copilot uses the selected project’s tasks and priorities.</p></div>}</div>}

createRoot(document.getElementById('root')).render(<App/>);
